# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, help_text='The username of your GitHub account.', max_length=39, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='The username of your Twitter account.', max_length=15, null=True, unique=True),
        ),
    ]
