# Generated by Django 1.11 on 2018-10-12 18:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20181012_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
