# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20181012_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='github_repo',
            field=models.CharField(blank=True, max_length=81, null=True, unique=True),
        ),
    ]
