# Generated by Django 1.11 on 2018-10-12 23:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_entry_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='head_sha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
