# Generated by Django 1.11 on 2018-10-13 07:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_entry_head_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ten Single Votes'), (1, 'Select Many'), (2, 'Instant-Runoff'), (3, 'Poll')], help_text='Instant-runoff is the type for challenge theme polls.'),
        ),
    ]
