# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-12 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20181013_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='is_rego_open',
            field=models.BooleanField(default=False, help_text=b'Set to True to open registration for this competition now. Otherwise, registration opens 45 days before the competition.'),
        ),
    ]
