# Generated by Django 3.2.6 on 2021-08-09 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0008_auto_20190807_1808_squashed_0011_auto_20190807_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_rego_open',
            field=models.BooleanField(default=False, help_text='Set to True to open registration for this competition now. Otherwise, registration opens 45 days before the competition.'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='theme_poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_challenge', to='challenge.poll'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='torrent_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diarycomment',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='last_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.diarycomment'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='game',
            field=models.CharField(help_text='The name of the game itself.', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='group_url',
            field=models.URLField(blank=True, help_text='Chat/group URL, visible only to participants.', null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Can people request to join the team?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='The name of the team that created the entry.', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='entry owner'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='entryaward',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='entryaward',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenge.challenge'),
        ),
        migrations.AlterField(
            model_name='file',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.IntegerField(choices=[(0, 'Ten Single Votes'), (1, 'Select Many'), (2, 'Instant-Runoff'), (3, 'Poll')], help_text='Instant-runoff is the type for challenge theme polls.'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='fun',
            field=models.PositiveIntegerField(choices=[(1, 'Not at all'), (2, 'Below average'), (3, 'About average'), (4, 'Above average'), (5, 'Exceptional')], default=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='innovation',
            field=models.PositiveIntegerField(choices=[(1, 'Not at all'), (2, 'Below average'), (3, 'About average'), (4, 'Above average'), (5, 'Exceptional')], default=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='production',
            field=models.PositiveIntegerField(choices=[(1, 'Not at all'), (2, 'Below average'), (3, 'About average'), (4, 'Above average'), (5, 'Exceptional')], default=3),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='response',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='challenge.option'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Checksum',
        ),
    ]
